name: Deploy to Elastic Beanstalk (EB CLI)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install EB CLI & awscli
        run: |
          python -m pip install --upgrade pip
          pip install awsebcli awscli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Verify AWS identity (debug)
        run: aws sts get-caller-identity

      - name: (Optional) Show .elasticbeanstalk folder
        run: ls -la .elasticbeanstalk || echo ".elasticbeanstalk not present"

      - name: Initialize EB non-interactively
        run: |
          # eb init "swe1-app" --region us-west-2 --platform "Python 3.12 running on 64bit Amazon Linux 2023"

      - name: Deploy to Elastic Beanstalk
        env:
          AWS_REGION: us-west-2
        run: |
          # Use the environment name shown in your local `eb status` output:
          eb status
          eb deploy django-env --region us-west-2 --label "${{ github.sha }}"
